### ISSUE TITLE
スクロールで死ぬ

### ISSUE THREAD

**Issue by mohemohe** [mstdn-plusminus-io/mastodon#55]
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at gs (https://mstdn.plusminus.io/packs/js/common-4ca260e107722e69d019.js:2:1041860)
    at wu (https://mstdn.plusminus.io/packs/js/common-4ca260e107722e69d019.js:2:1055061)
    at https://mstdn.plusminus.io/packs/js/common-4ca260e107722e69d019.js:2:1075575
    at Va (https://mstdn.plusminus.io/packs/js/common-4ca260e107722e69d019.js:2:1000226)
    at _u (https://mstdn.plusminus.io/packs/js/common-4ca260e107722e69d019.js:2:1052921)
    at su (https://mstdn.plusminus.io/packs/js/common-4ca260e107722e69d019.js:2:1049075)
    at https://mstdn.plusminus.io/packs/js/common-4ca260e107722e69d019.js:2:1000517
    at https://mstdn.plusminus.io/packs/js/common-4ca260e107722e69d019.js:2:1075575
    at Va (https://mstdn.plusminus.io/packs/js/common-4ca260e107722e69d019.js:2:1000226)
    at Ya (https://mstdn.plusminus.io/packs/js/common-4ca260e107722e69d019.js:2:1000462)

Ki (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5411:106)
Mi (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6363:21)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:309:11)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2816:9)
Jj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6204:2)
Kj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5895:4)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2851:16)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:309:11)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2816:9)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2846:6)

**Comment by mohemohe** [comment]
ところで: なんでSourceMapが無いんだ

**Comment by mohemohe** [comment]
https://github.com/mstdn-plusminus-io/mastodon/blob/master/app/javascript/mastodon/components/intersection_observer_article.js#L64 で起きてる

**Comment by mohemohe** [comment]
これ一旦stackTraceLimitをInifinityにしないと話にならんな

**Comment by mohemohe** [comment]
Sourcesタブでformatしなければいけた

DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at HTMLDivElement.removeChild (<anonymous>)
    at gs (https://mstdn.plusminus.io/packs/js/common-4ca260e107722e69d019.js:2:1041860)
    at wu (https://mstdn.plusminus.io/packs/js/common-4ca260e107722e69d019.js:2:1055061)
    at https://mstdn.plusminus.io/packs/js/common-4ca260e107722e69d019.js:2:1075575
    at Va (https://mstdn.plusminus.io/packs/js/common-4ca260e107722e69d019.js:2:1000226)
    at _u (https://mstdn.plusminus.io/packs/js/common-4ca260e107722e69d019.js:2:1052921)
    at su (https://mstdn.plusminus.io/packs/js/common-4ca260e107722e69d019.js:2:1049075)
    at https://mstdn.plusminus.io/packs/js/common-4ca260e107722e69d019.js:2:1000517
    at https://mstdn.plusminus.io/packs/js/common-4ca260e107722e69d019.js:2:1075575
    at Va (https://mstdn.plusminus.io/packs/js/common-4ca260e107722e69d019.js:2:1000226)
overrideMethod @ react_devtools_backend.js:2430
as @ react-dom.production.min.js:5058
o.componentDidCatch.n.callback @ react-dom.production.min.js:5590
go @ react-dom.production.min.js:3108
cs @ react-dom.production.min.js:5166
wu @ react-dom.production.min.js:6408
(anonymous) @ scheduler.production.min.js:309
Va @ react-dom.production.min.js:2816
_u @ react-dom.production.min.js:6204
su @ react-dom.production.min.js:5895
(anonymous) @ react-dom.production.min.js:2851
(anonymous) @ scheduler.production.min.js:309
Va @ react-dom.production.min.js:2816
Ya @ react-dom.production.min.js:2846
Xa @ react-dom.production.min.js:2836
nu @ react-dom.production.min.js:5678
enqueueSetState @ react-dom.production.min.js:3137
(anonymous) @ react.production.min.js:55
(anonymous) @ intersection_observer_article.js:64
(anonymous) @ intersection_observer_wrapper.js:19
(anonymous) @ intersection_observer_wrapper.js:16

**Comment by mohemohe** [comment]
Twemoji Everywhereでblacklistに入れたら問題なくなった
でもreplaceしただけでremoveChildが失敗するのはそれはそれでどうなん？って感じがある

**Comment by mohemohe** [comment]
まあいいやってことで
